config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get "home" => 'static_pages#home'
  get "help" => 'static_pages#help'
  get "about" => 'static_pages#about'
  get "contact" => 'static_pages#contact'
  get "newuser" => 'users#new'
  get "address" => 'addresss#index'
  get "login" => 'sessions#new'
  post "login" => 'sessions#create'
  delete "logout" => 'sessions#destroy'
  resources :users
  resources :address
  
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name , presence: true, length: {maximum: 50}, uniqueness: true
    validates :email , presence: true  
    has_secure_password
end

app/controllers/addresss_controller.rb
class AddresssController < ActionController::Base
  protect_from_forgery with: :exception
  
  def index
    puts "modify check"  
    render html: "Hello World!"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def say_hello
    puts "modify check"  
    render html: "Hello World!"
  end
  
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if !user.nil? && user.authenticate(params[:session][:password])
      #success scenario
      log_in user
      current_user
      redirect_to user_url(user)
    else
      #failure scenario - some one is trying to login into system
      redirect_to :action => "create"
    end
  end
  
  def destroy
    log_out 
    redirect_to root_url 
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
  def help
  end

  def about
  end
  
  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end
  
  def show
    @user = User.find params[:id]
  end
  
  def create
   @user = User.new(user_params)
   if(@user.save)
     puts "user saved successfully"
     redirect_to user_url(@user)
    else
      render "new"
    end  
  end
  
  private
  def user_params
    params.require(:user).permit(:name , :email , :password , :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def get_base_title(pageTitle = "")
        pageTit = "Ruby Rails Page"
        if pageTitle != ""
           pageTit = "Ruby Rails #{pageTitle} Page" 
        end    
        pageTit
    end    
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user()
        @currentUser = @currentUser ||User.find_by(id: session[:user_id]) 
    end
    
    def logged_in?
        current_user
        puts "current user is "
        puts @currentUser
        puts @currentUser.nil?
        !@currentUser.nil?
    end
    
    def log_out
        session.delete :user_id
        @currentUser = nil;
    end    
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    
    def get_page_name(pageName = "")
        pageNam = pageName
        if pageName == ""
           pageNam = "home" 
        end    
        pageNam
    end 
    
end

app/helpers/users_helper.rb
module UsersHelper
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>

    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>

    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>

  </small>

  <nav>

    <ul>
          <li><%= link_to "About", about_path %></li>

      <li><%= link_to "Contact", contact_path %></li>

      <li><a href="http://news.railstutorial.org/">News</a></li>

    </ul>

  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Sample APP", root_path , {id: "logo"} %>
      </div>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "home",root_path , {id: "home"} %></li>
          <li><%= link_to "help",help_path , {id: "help"} %></li>
          <% if logged_in? %>
          <li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
          <% else %>
          <li><%= link_to "login",login_path , {id: "login"} %></li>
          <% end %>
        </ul> 
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= get_base_title(yield :title)%>
      
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <li><%= link_to image_tag("Ruby_on_Rails-logo.png", alt: "rails logo" , size: "20x20"), "https://www.tutorialspoint.com/ruby-on-rails/" %></li>
    
      <%= render 'layouts/footer' %>
      
  </body>
</html>

app/views/shared/_form_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">

    <div class="alert alert-danger">

      The form contains <%= pluralize(@user.errors.count, "error") %>.

    </div>

    <ul>

    <% @user.errors.full_messages.each do |msg| %>

      <li><%= msg %></li>

    <% end %>

    </ul>

  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title , "about") %>

  <h1>About page</h1>
  <p>This is the about page of <a href="https://www.youtube.com/"><%= get_page_name yield(:title)%> page !</a></p>

app/views/static_pages/contact.html.erb
<% provide(:title , "contact") %>

  <h1>Contact Info</h1>
  <p>This is the Contact page of 
  <a href="https://www.tutorialspoint.com/ruby-on-rails/"><%= get_page_name yield(:title)%> page !</a></p>

app/views/static_pages/help.html.erb
<% provide(:title , "help") %>
<h1>Help page</h1>
<p>This is the help page of <a href="https://www.yahoo.com/"><%= get_page_name yield(:title)%> page !</a></p>

app/views/static_pages/home.html.erb
    <div class= "jumbotron center">
    <body>
        <h1>Welcome to sample APP</h1>
        <h2>This is the home page for
            <a href="https://www.tutorialspoint.com/ruby-on-rails/">ruby on rails tutorial</a>
            sample application
        </h2>
        <li><%= link_to "Sign Up now", newuser_path , {class: "btn btn-lg btn-primary"} %></li>
    </body>
    </div>

app/views/users/new.html.erb
<% provide :title , "Sign up"%>
<h1>Register</h1>
<p>please enter your details to register</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render "shared/form_error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title , " Welcome" + @user.name) %>
<br>
<h3>Welcome <%= @user.name%></h3>
<p>
    <br>
    User name : <%= @user.name%>
    <br>
    User name : <%= @user.email%>
</p> 
    